dist: xenial
#language: cpp
language: python
python: "3.7"
compiler: clang

# install and set g++-8 and boost
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libboost-test-dev
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
before_install:
    - eval "${MATRIX_EVAL}"
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 60

# Install conan
install:
  - pip3 install conan
  # Automatic detection of your arch, compiler, etc.
  - conan user
  
# run
script:
- conan install .
# mf costyl': need to update conan profile and install again
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 60
- conan profile update settings.compiler.libcxx=libstdc++11 default
- conan profile update settings.compiler.version=8 default 
- conan install .
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package


deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T range-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ugwqw:$BINTRAY_API_KEY "https://api.bintray.com/content/gwqw/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/range-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
